#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

# Check if the number of parameter is less than 4
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Use scp to transfer the file to the user's home directory on the server
if scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/; then
	echo "File transferred successfully"
else
	echo "Error: File transfer failed"
fi

