#!/usr/bin/env bash
#Bash script that displays: 
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyound"
	sleep 2
	trap 'echo "I am invincible!!!' SIGTERM
done
