#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100

for ((i=1; i<=100; i++)); do
	if ((i%3 == 0 && i%5 == 0)); then
		echo "FizzBuzz"
	elif((i%3 == 0)); then
		echo "Fizz"
		continue
	elif ((i%5==0)); then
		echo "Buzz"
		continue
	else
		echo "$i"
	fi
done
		

