#!/usr/bin/env bash
#Thescript is used to print "Best school" and "if" insidethe loop
# on the 9th itertion, display "Hi" before "Best School".

i=0

while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
		((i++))
		continue
	fi
	echo "Best School"
	((i++))
done
