#!/usr/bin/env bash
#Thescript is used to print "Best school" and "if" insidethe loop

i=1

while [ $i -lt 10 ]; do
	((i++))
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
done
