#!/usr/bin/env bash
# This script echo "Best School" and "Bad luck" in the 4th itertion and "Good luck in the 8 iteration"

i=1

while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
		((i++))
		continue
	elif [ $i -eq 8 ]; then
		echo "good luck"
		((i++))
		continue
	else
		echo "Best School"
		((i++))
	fi
done



