#!/usr/bin/env bash
# This script echo "Best School" and "Bad luck" in the 4th itertion and "Good luck in the 8 iteration"

for ((i=1; i<=10; i++)); do
	if ((i==4)); then
		echo "bad luck"
	elif ((i==8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
done

