#!/usr/bin/env bash
# Create a case statement

i=1

while [ $i -le 20 ]; do
	case $i in 
		4)
			echo $i
			echo "bad luck from china"
			;;
		9)
			echo $i
			echo "bad luck from Japan"
			;;
		17)
			echo $i
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac

	((i++))
done
