#!/usr/bin/env bash
# The script print the time

hours=0
minutes=1

while [ "$hours" -lt 12 ]; do
	echo "Hour: $hours"
	while [ "$minutes" -le 59 ]; do
		echo "$minutes"
		((minutes++))

	done
	((hours++))
	minutes=1
done
