#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory; In a list format

for file in *; do
	if [ -f "$file" ] && [[ "$file" != .* ]]; then
		name=${file#*-}
		echo "$name"
	fi
done
